### ISSUE TITLE
Add an --out option. And by default, console.log out the swagger file.

### ISSUE THREAD

**Issue by gkoberger** [readmeio/swagger-inline#1]
**Problem:** I keep using `swagger.json` as my base, and I keep mistakenly overwriting it.

**Solution:** By default, let's make it just `console.log` out the Swagger result. Let's also add an `--out` option for choosing a place to write it to. If the `--out` value ends with `.json`, write it as JSON. If it's `.yaml`, write it as YAML.

**Bonus Points:** Maybe we can also add a `--format` option that lets you choose the format (so you can use `.yaml` as the `--base`, but output it as JSON). It'll also let you be specific if your `--out` file doesn't have a proper extension.

**Comment by haroldtreen** [comment]
Format option already exists 👍 

![image](https://cloud.githubusercontent.com/assets/1745854/18655863/48cecfde-7eba-11e6-93dc-88bcae7c5c84.png)

Out option shouldn't be hard. And can also override the format option with any filetype used for `--out`.

**Comment by haroldtreen** [comment]
Going to make it so that when you include `--out` it logs the feedback (eg. "Why do you have 15 swagger.json files?"). If you don't include that, the only thing logged is the result. Then you can pipe the results to other crazy unix commands :).

**Comment by gkoberger** [comment]
That sounds great!

**Comment by haroldtreen** [comment]
Added!

![image](https://cloud.githubusercontent.com/assets/1745854/18657546/3aa035ce-7ec9-11e6-9716-79d66f54a4fc.png)

### Changes:
- `--out` is now the final say on the output filetype
- Including `--out` for the Cli or the module will cause the file to be written to the provided path.
- Including `--out` will cause the Cli to log progress messages and such.
- Omitting `--out` will disable all logging. The output will either be the final `swagger` or an error message if things really blow up.

**Comment by haroldtreen** [comment]
Re-open if it gives you problems, otherwise closing this downnn 👇

**Comment by gkoberger** [comment]
This looks great! :)
