### ISSUE TITLE
Intent to deprecate: multi-glob

### ISSUE THREAD

**Issue by dominykas** [readmeio/swagger-inline#100]
Hey folks,

sorry to bother you about this, but it seems like there isn't anyone around who has the capacity to keep `multi-glob` maintained. It has not been in active development for a while now and so we intend to mark it deprecated and archive the repo.

`swagger-inline` is one of the largest dependents (by download count), and the download numbers are not entirely insignificant, so we wanted to give you folks a heads up before we do so (the plan is to run `npm deprecate` in some 30 days).

In terms of what happens next - would you mind forking the package and releasing it under your own namespace or finding an alternative on npm that already exists?

Thanks!

cc @mroderick

**Comment by erunion** [comment]
Thanks for the heads up!
