### ISSUE TITLE
command not found: swagger-inline

### ISSUE THREAD

**Issue by fabioperrella** [readmeio/swagger-inline#124]
Hi there!!

Just after installing the package (with `npm install --save-dev swagger-inline`), I can't run the command `swagger-inline`

```bash
$ swagger-inline
zsh: command not found: swagger-inline
```

I don't have too much experience with npm, is there any trick to "enable" the binary?

Tks!

**Comment by fabioperrella** [comment]
humm, I think I found the answer here! https://stackoverflow.com/questions/9679932/how-to-use-executables-from-a-package-installed-locally-in-node-modules

**Comment by erunion** [comment]
👍  You can also do `npx swagger-inline` and that'll either install it and run it from your global home directory, or if it's installed in the project your'e working in, use the version that project.
