### ISSUE TITLE
Write errors to stderr 

### ISSUE THREAD

**Issue by Morten1337** [readmeio/swagger-inline#178]
In src/cli.js the program errors are written out with console.log.

Consider using console.error instead so that stderr and stdout can be redirected separately.

Like in my case I only want the the swagger output written to a file, and if there is a parsing error, I'd like to see that in the shell.

```bash
swagger-inline "./*.js" --base 'swaggerBase.json' 2>&1 > api.json
```

```diff
    .catch(err => {
-      console.log('An error occured:');
-      console.log(err);
+      console.log('An error occured:');
+     console.log(err);
      process.exit(-1);
    });
```

**Comment by erunion** [comment]
@Morten1337 If you're up for submitting a pull request we'll happily pull it in.

**Comment by erunion** [comment]
Done in https://github.com/readmeio/swagger-inline/pull/179
