### ISSUE TITLE
Search for base if it doesn't exist

### ISSUE THREAD

**Issue by gkoberger** [readmeio/swagger-inline#2]
To make this a bit easier, let's try to find the `--base` if they don't input it. We can search all files in the directory, and look for `.yaml` and `.json` files.

- [ ] If there's none, throw a warning ("It works better if you have a base file!"), along with a description of how to do that.
- [ ] If there's more than one, print out the options (along with the command needed to make it happen).

**Comment by haroldtreen** [comment]
Donezo! 💥 

https://github.com/readmeio/swagger-inline/commit/6c45dde6495687f87223e3236f6ec96d605f4b80

![image](https://cloud.githubusercontent.com/assets/1745854/18658677/19efe2e8-7ed3-11e6-8d37-c315938efe11.png)

**Comment by gkoberger** [comment]
Sweet!
