### ISSUE TITLE
What's the value of this?

### ISSUE THREAD

**Issue by Evanlec** [readmeio/swagger-inline#21]
All this does is concatenate comments into a swagger.json file.

No code introspection? What about leveraging express.js to auto-discover the API endpoints automatically. Then inspect the code to generate the route parameters.
The whole point is, I don't want to write a separate swagger.json file that I have to maintain. 

Updating the code itself should be enough to also update the documentation, automatically. 

Some in-line annotations, like is done with the Java/Swagger/OpenAPI tool set, are added to allow one to add things like API endpoint descriptions and the like. But the parameters and such are all dynamically generated.

**Comment by erunion** [comment]
Auto-discovery and creating an OAS that way is available with other tools as you've mentioned, swagger-inline is just an option for people who'd like to explicitly document their APIs alongside their code.

Really, it just comes down to preference.
