### ISSUE TITLE
Parameter shorthand schema instead of type

### ISSUE THREAD

**Issue by jegsar** [readmeio/swagger-inline#212]
Given the example `- (body) complicatedPet {Object} the pet` {} seems to use the type property. Is there a way to have it use schema instead so it could be `- (body) complicatedPet {Pet} the pet` or `- (body) complicatedPet {#/components/schemas/Pet} the pet`?

**Comment by Khauri** [comment]
Hi, I would be willing to submit a PR for this. I think this could also potentially help with specifying arrays of items (unless there's a way to do this already that I'm missing?).

I'm imagining this would be simple enough to add to [expandParam](https://github.com/readmeio/swagger-inline/blob/main/src/loader.js#L174).

Would 
```
- (body) complicatedPet {#/components/schemas/Pet} the pet
``` 
be the preferred syntax here? I would imagine that
```
- (body) complicatedPet {Pet} the pet
```
would be implemented by inferring the `#/components/schemas` prefix whenever there's no match for one of the open api data types (which I don't believe are formally defined in this codebase?) which would add some complexity, whereas the former, while verbose, only requires that you check the type starts with `#`.

Another option could be

```
- (body) complicatedPet {ref:Pet} the pet
# or
- (body) complicatedPet {schema:Pet} the pet
```

Which is easier to look at and is similar to the `type:format` syntax already used.

**Comment by erunion** [comment]
If you want to submit a PR, please do! This library already supports composing full OpenAPI schemas within docblocks so this would be nice to have for folks to use the shorthand style.

I like `- (body) complicatedPet {schemas:Pet} the pet` as that'll let you specify which component schema type it is.

**Comment by erunion** [comment]
I'm happy with that format you suggested:

```
- (body) complicatedPet {ref:schemas/Pet} the pet
```

My main concern is that it should let you be able to load in `schemas/*` or `requestBodies/*` or` parameters/*` or whatever you'd like and that would work with that format above.

**Comment by erunion** [comment]
This is now supported in [v5.2.0](https://github.com/readmeio/swagger-inline/releases/tag/5.2.0), Thanks @Khauri!
