### ISSUE TITLE
Clarify difference between this project and oas

### ISSUE THREAD

**Issue by sandstrom** [readmeio/swagger-inline#227]
Would be neat if your readme (or wiki) had a comparison table between this project and oas. Pros/cons, where you'd recommend each one, etc.

https://github.com/readmeio/oas

*see also https://github.com/readmeio/oas/issues/539*

**Comment by kanadgupta** [comment]
Hi @sandstrom — the CLI functionality in `oas` was removed in https://github.com/readmeio/oas/pull/702 so there is virtually no overlap between this library and `oas` now. Apologies for the delay!
