### ISSUE TITLE
Supporting tabs vs spaces in comments

### ISSUE THREAD

**Issue by garrett-wade** [readmeio/swagger-inline#251]
Looking into error where inline comments require spaces, but our dev organization uses tabs. Error below:

![image](https://user-images.githubusercontent.com/42807642/158894420-9dcb39b6-4bbf-448f-b483-83d14e6fb483.png)

**Comment by erunion** [comment]
Resolved in https://github.com/readmeio/swagger-inline/pull/252 and v5.1.1.
