### ISSUE TITLE
Errors not surfaced

### ISSUE THREAD

**Issue by gkoberger** [readmeio/swagger-inline#3]
In the `swaggerInline` version of stuff (Like, not the command line. The Node version), errors aren't ever surfaced.

For example, this was never surfaced (until I ran it via the command line):

![image](https://cloud.githubusercontent.com/assets/381393/19017626/e66a65ac-87f5-11e6-8f9f-98068076607f.png)

(@haroldtreen, you're busy so don't worry about this! I'm just throwing stuff in Issues)

**Comment by haroldtreen** [comment]
So in the CLI version, `console.log` is passed as a logger for errors.
If you do that for the node version, should be surfaced in the same way.

It doesn't explode though... maybe the promise should reject if anything fails to parse.

If passing the logger works, then awesome. 
If having it reject would be better, can change it to that too.

**Comment by gkoberger** [comment]
Nope, I think a logger is good enough! I just hadn't realized :)
