### ISSUE TITLE
Are there any plans to support Open API 3.0.0?

### ISSUE THREAD

**Issue by imposibrus** [readmeio/swagger-inline#8]

**Comment by dwasyluk** [comment]
Any updates on this?

**Comment by gkoberger** [comment]
Yes! We were waiting on the package `swagger-parser` to support it, however we'll be switching to `wework/speccy` instead. We hope to have it out soon!

**Comment by gkoberger** [comment]
Should now support OAS 3! It might not support everything, so let me know if you run into trouble :)
