### ISSUE TITLE
scope example?

### ISSUE THREAD

**Issue by x37v** [readmeio/swagger-inline#94]
I'm not seeing `scope` in the open api spec: https://swagger.io/specification except for in the `OAuth Flow Object`.

Can you provide an example where you put these settings in docs?

I have an API that has both public and private parts, I would love to render them into different documents. This seems like an approach because the tool allows for filtering by scope, but I don't actually understand how to use it.

Thanks

**Comment by erunion** [comment]
`scope` in this context doesn't match up with OAuth flow scopes, but yeah filtering generated API definitions based on a set of scopes (like public or private).

We use this in the ReadMe Metrics API to generate two OAS files, one for the entire API and one for just our public-facing operations and we do this by adding a `scope: public` entry into our inline definitions as such:

```js
/**
 * @api [get] /pets
 * scope: public
 * description: "Returns all pets from the system that the user has access to"
 * responses:
 *   "200":
 *     description: "A list of pets."
 *     schema:
 *       type: "String"
 */

/**
 * @api [post] /pets
 * description: "Creates a new pet
 * responses:
 *   "200":
 *     description: "The created pet."
 */
```

Then you can supply `swagger-inline` with `--scope public` and only those operations with `scope: public` get picked up. Omit `--scope public` and everything will be picked up.

Hopefully that helps!

**Comment by x37v** [comment]
ahh, I get it.
it could be helpful `scope: public` in the example given in the README.

**Comment by erunion** [comment]
Done! https://github.com/readmeio/swagger-inline#scoped-compilations
